minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.110.5'
  - '@supabase/functions-js@2.110.5'
  - '@supabase/postgrest-js@2.110.5'
  - '@supabase/realtime-js@2.110.5'
  - '@supabase/storage-js@2.110.5'
  - '@supabase/supabase-js@2.110.5'
  - react-native-url-polyfill@4.0.0
